version: '3'
services:
  airflow:
    image: apache/airflow:2.9.2
    container_name: airflow
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY:-testfernetkey123}
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=utc
      - TZ=UTC
      # Metadata DB (Use a separate Postgres container)
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      # Email
      - AIRFLOW__EMAIL__EMAIL_BACKEND=airflow.utils.email.send_email_smtp
      - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
      - AIRFLOW__SMTP__SMTP_PORT=587
      - AIRFLOW__SMTP__SMTP_USER=2551aaf494a9cd
      - AIRFLOW__SMTP__SMTP_PASSWORD=95893e31ee9985
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=test@example.com
      # Python
      - _PIP_ADDITIONAL_REQUIREMENTS=-r /opt/airflow/dags/requirements.txt
      # S3 and RDS connections
      - S3_BUCKET_NAME=apartments-data-lake-raw
      - DB_HOST=apartments-rds.c5yi466cgccj.us-west-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_NAME=apartment_db
      - DB_SECRET_ARN=arn:aws:secretsmanager:us-west-1:493504727387:secret:apartments/db_credentials-gymN1f
      # use the credentials from EC2 binded IAM role
      - AWS_EC2_METADATA_DISABLED=false
      # for ECS Operator and other AWS interactions
      - AWS_DEFAULT_REGION=us-west-1 # for ECS Operator and other AWS interactions
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /etc/localtime:/etc/localtime:ro # make sure the time is in sync with the host (S3 will check the time)
    networks:
      - shared-network
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --password admin123 --firstname EC2 --lastname Airflow --role Admin --email admin@example.com &&
               airflow webserver -p 8080 & exec airflow scheduler"
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - shared-network

volumes:
  postgres-db-volume:

networks:
  shared-network:
